services:
  - type: web
    name: church-management-system
    env: python
    plan: free  # 👈 this is important
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn church_management_system.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: church_management_system.settings
